Assignments 07.05.24 IF Statements
CynthiaWahome/pythonSprint pull request #1
Opened 2024-05-08 02:21 UTC by CynthiaWahome

Assignment on chapter_02
1. life_stages.py
2. favorite_fruit.py
3. ordinal_numbers.py

Note to Self:
I wanted this branch to only have assignments. How can I remove the other folders

2024-05-08 09:54 UTC, ProgramKingAbel requested changes
#1 Good Job
Job well done ... You have a strong grasp of the if conditional statements. 

- [ ] You cannot have a branch solely for assignments ... a specific folder dedicated to that within the main branch would do. You checkout and do the tests on the assignments folder for each chapter.

2024-05-08 09:54 UTC, ProgramKingAbel commented on chapter_3/favourite_fruit.py
> +    print("Iza joh! That fruit is not in the list")
Good job implementing the if statements:

- [ ] Remove the else block as it is only tied to the last if statement

2024-05-08 09:54 UTC, ProgramKingAbel commented on chapter_3/ordinal_numbers.py
> +        print(num,"th")
syntax is okay but for the logic, consider using the following in the last statement:

`elif num > 3 or num < 10`

for your condition

2024-05-09 06:34 UTC, CynthiaWahome commented
Thanks @ProgramKingAbel 
These changes have been implemented

2024-05-09 06:34 UTC, merged